datasets:
  ET:
    url: "https://github.com/zhouhaoyi/ETDataset"
    type: "gitRepository"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      ETTh1: ["ETT-small", "ETTh1.csv"]
      ETTh2: ["ETT-small", "ETTh2.csv"]
      ETTm1: ["ETT-small", "ETTm1.csv"]
      ETTm2: ["ETT-small", "ETTm2.csv"]
  electricityUCI:
    url: "https://archive.ics.uci.edu/static/public/321/electricityloaddiagrams20112014.zip"
    type: "zip"
    format: "csv"
    separator: ";"
    decimal: ","
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      electricity: ["LD2011_2014.txt"]
  m4-monthly:
    url: "https://zenodo.org/records/4656480/files/m4_monthly_dataset.zip?download=1"
    type: "zip"
    format: "monash"
    separator: ","
    decimal: "."
    periodicity:
      month: 1
    timeformat: "%Y-%m-%d %H-%M-%S"
    subdatasets:
      m4-monthly: ["m4_monthly_dataset.tsf"]
  solarEnergy:
    url: "https://zenodo.org/records/4656151/files/solar_weekly_dataset.zip?download=1"
    type: "zip"
    format: "monash"
    separator: ","
    decimal: "."
    periodicity:
      week: 1
    timeformat: "%Y-%m-%d %H-%M-%S"
    subdatasets:
      solarEnergy: ["solar_weekly_dataset.tsf"]
  power:
    url: "https://www.kaggle.com/datasets/dharanikra/electrical-power-demand-in-turkey"
    type: "kaggle"
    datasetName: "dharanikra/electrical-power-demand-in-turkey"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%d.%m.%Y %H:%M"
    subdatasets:
      power : ["power Generation and consumption.csv"]
monash:
  timeFormat: "%Y-%m-%d %H-%M-%S"
vectorDatabase:
  collections:
    moiraiMoE:
      all: moiraiMoE_all
    chatTime:
      all: chatTime_all
  distance:
    euclidean:
      hnsw:space: "l2"
paths:
  data: ["data"]
  datasets: ["data", "datasets"]
  vectorDatabase: ["data", "vectorDatabase"]
files:
  datasets: ["data", "datasets", "datasets.yaml"]
  evaluationReportsMoiraiMoE: ["data", "reportsMoiraiMoE.yaml"]
  evaluationFinalReport: ["data" ,"reports.pdf"]