seed: 42
trainPartition: 0.8
maxTestSamples: 10000
datasets:
  ET:
    url: "https://github.com/zhouhaoyi/ETDataset"
    type: "gitRepository"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      ETTh1: ["ETT-small", "ETTh1.csv"]
      ETTh2: ["ETT-small", "ETTh2.csv"]
      ETTm1: ["ETT-small", "ETTm1.csv"]
      ETTm2: ["ETT-small", "ETTm2.csv"]
  huaweiCloud:
    url: "https://github.com/sir-lab/time-series-fm-dataset.git"
    type: "gitRepository"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      datacenter1: ["data", "datacentre_1.zip"]
      datacenter2: ["data", "datacentre_2.zip"]
      datacenter3: ["data", "datacentre_3.zip"]
      datacenter4: ["data", "datacentre_4.zip"]
  electricityUCI:
    url: "https://archive.ics.uci.edu/static/public/321/electricityloaddiagrams20112014.zip"
    type: "zip"
    format: "csv"
    separator: ";"
    decimal: ","
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      electricity: ["LD2011_2014.txt"]
  m4-monthly:
    url: "https://zenodo.org/records/4656480/files/m4_monthly_dataset.zip?download=1"
    type: "zip"
    format: "monash"
    separator: ","
    decimal: "."
    periodicity:
      month: 1
    timeformat: "%Y-%m-%d %H-%M-%S"
    subdatasets:
      m4-monthly: ["m4_monthly_dataset.tsf"]
  solarEnergy:
    url: "https://zenodo.org/records/4656151/files/solar_weekly_dataset.zip?download=1"
    type: "zip"
    format: "monash"
    separator: ","
    decimal: "."
    periodicity:
      week: 1
    timeformat: "%Y-%m-%d %H-%M-%S"
    subdatasets:
      solarEnergy: ["solar_weekly_dataset.tsf"]
  power:
    url: "https://www.kaggle.com/datasets/dharanikra/electrical-power-demand-in-turkey"
    type: "kaggle"
    datasetName: "dharanikra/electrical-power-demand-in-turkey"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%d.%m.%Y %H:%M"
    subdatasets:
      power : ["power Generation and consumption.csv"]
  traffic:
    url: "https://www.kaggle.com/datasets/leonardo00/istanbul-traffic-index"
    type: "kaggle"
    datasetName: "leonardo00/istanbul-traffic-index"
    format: "csv"
    separator: ","
    decimal: "."
    timeformat: "%Y-%m-%d %H:%M:%S"
    subdatasets:
      traffic : ["istanbul_traffic.csv"]
  cloud:
    url: https://github.com/BizITObs/BizITObservabilityData/tree/main/Complete/Time%20Series/L2C
monash:
  timeFormat: "%Y-%m-%d %H-%M-%S"
vectorDatabase:
  maxNumberSamples: 10000
  scoreThreshold : 0.1
  k : 10
  collections:
    chatTimeCosine_32_16:
      metric:
        hnsw:space: "cosine"
      context: 32
      prediction: 16
      datasets: [
        "ET",
        "solarEnergy",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
    chatTimeCosine_64_16:
      metric:
        hnsw:space: "cosine"
      context: 64
      prediction: 16
      datasets: [
        "ET",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
    chatTimeCosine_128_16:
      metric:
        hnsw:space: "cosine"
      context: 128
      prediction: 16
      datasets: [
        "ET",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
    moiraiMoECosine_32_16:
      metric:
        hnsw:space: "cosine"
      context: 32
      prediction: 16
      datasets: [
        "ET",
        "solarEnergy",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
    moiraiMoECosine_64_16:
      metric:
        hnsw:space: "cosine"
      context: 64
      prediction: 16
      datasets: [
        "ET",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
    moiraiMoECosine_128_16:
      metric:
        hnsw:space: "cosine"
      context: 128
      prediction: 16
      datasets: [
        "ET",
        "power",
        "m4-monthly",
        "traffic",
        "huaweiCloud",
      ]
paths:
  data: ["data"]
  datasets: ["data", "datasets"]
  vectorDatabase: ["data", "vectorDatabase"]
files:
  datasets: ["data", "datasets", "datasets.yaml"]
  databaseTracking: ["data", "databaseTracking.yaml"]
  evaluationReportsMoiraiMoE: ["data", "reportsMoiraiMoE.yaml"]
  evaluationReportsMoiraiMoERag: ["data", "reportsMoiraiMoERag.yaml"]
  evaluationReportsChatTime: ["data", "reportsChatTime.yaml"]
  evaluationReportsChatTimeRag: ["data", "reportsChatTimeRag.yaml"]
  evaluationFinalReportMoiraiMoE: ["data" ,"reportsMoiraiMoE.pdf"]
  evaluationFinalReportChatTime: ["data" ,"reportsChatTime.pdf"]
  evaluationFinalReportMoiraiMoERag: ["data", "reportsMoiraiMoERag.pdf"]
  evaluationFinalReportChatTimeRag: ["data", "reportsChatTimeRag.pdf"]