datasets:
  ET:
    url: "https://github.com/zhouhaoyi/ETDataset"
    type: "gitRepository"
    separator: ","
    decimal: "."
    subdatasets:
      ETTh1: ["ETT-small", "ETTh1.csv"]
      ETTh2: ["ETT-small", "ETTh2.csv"]
      ETTm1: ["ETT-small", "ETTm1.csv"]
      ETTm2: ["ETT-small", "ETTm2.csv"]
  electricityUCI:
    url: "https://archive.ics.uci.edu/static/public/321/electricityloaddiagrams20112014.zip"
    type: "zip"
    separator: ";"
    decimal: ","
    subdatasets:
      electricity: ["LD2011_2014.txt"]
  weatherMaxPlanckInstitut:
    url: "https://www.bgc-jena.mpg.de/wetter"
  m4-weekly:
    url: "https://zenodo.org/records/4656480"
    dataset : "monash"
  trafficCalifornia:
    url: "https://pems.dot.ca.gov"
  IllnessSurveillance:
    url: "https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html"
  solarEnergy:
    url: "https://zenodo.org/records/4656151"
    dataset: "monash"
  power:
    url: "https://www.kaggle.com/datasets/dharanikra/electrical-power-demand-in-turkey"
    dataset: "kaggle"
  trafficInstanbul:
    url: "https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html"
    dataset: "kaggle"
paths:
  data: ["data"]
  datasets: ["data", "datasets"]
files:
  datasets: ["data", "datasets", "datasets.yaml"]